const favoritos = document.getElementById('favoritos');
const nav_favoritos = document.getElementById('nav_favoritos');
const principal = document.getElementById('principal');
const nav_principal = document.getElementById('nav_principal');
const informes = document.getElementById('informes');
const nav_informes = document.getElementById('nav_informes');
const usuarios = document.getElementById('usuarios');
const nav_usuarios = document.getElementById('nav_usuarios');
const buzon = document.getElementById('buzon');
const nav_buzon = document.getElementById('nav_buzon');
const destacados = document.getElementById('destacados');
const nav_destacados = document.getElementById('nav_destacados');
const cargar = document.getElementById('cargar');
const nav_cargar = document.getElementById('nav_cargar');
const origen = document.getElementById('origen');
const config = document.getElementById('config');
const eliminar_us = document.getElementById('eliminar_us');
const rango_us = document.getElementById('rango_us');
const rango_us_prin = document.getElementById('rango_us_prin');
const rango_us_ascender = document.getElementById('rango_us_ascender');
const rango_us_degradar = document.getElementById('rango_us_degradar');
const sec_asc = document.getElementById('sec_asc');
const sec_deg = document.getElementById('sec_deg');
const info_usuario = document.getElementById('info_usuario');
const cambiar_nombre = document.getElementById('cambiar_nombre');
const cambiar_email = document.getElementById('cambiar_email');
const cambiar_contraseña = document.getElementById('cambiar_contraseña');
const desc = document.getElementById('descripcion');
var id;
function env_c(a) {
    const form = document.createElement("form");
    form.setAttribute("style", "display:none;");
    form.setAttribute("method", "POST");
    form.setAttribute("action", "cargar.php");
    const input = document.createElement("input");
    input.setAttribute("type", "text");
    input.setAttribute("value", a);
    input.setAttribute("name", "tabla");
    form.appendChild(input);
    const button = document.createElement("button");
    button.setAttribute("type", "submit");
    button.setAttribute("id", "envta");
    form.appendChild(button);
    document.body.appendChild(form);
    document.getElementById("envta").click();
}